{"uuid": "50f040d3-e6f1-428f-a45c-51b0fb608131", "children": ["ec4c38ab-5b16-48d9-a637-c2af2782159c"], "befores": [{"name": "setup_Login_dos", "status": "passed", "start": 1751938051190, "stop": 1751938075767}], "afters": [{"name": "setup_Login_dos::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection\n\n", "trace": "  File \"C:\\Users\\saul.frias\\PycharmProjects\\SeleniumProject\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\saul.frias\\PycharmProjects\\SeleniumProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\saul.frias\\PycharmProjects\\SeleniumProject\\PYTEST\\Fixture_decorate2.py\", line 56, in setup_Login_dos\n    driver.close()\n    ~~~~~~~~~~~~^^\n  File \"C:\\Users\\saul.frias\\PycharmProjects\\SeleniumProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 579, in close\n    self.execute(Command.CLOSE)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"C:\\Users\\saul.frias\\PycharmProjects\\SeleniumProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\saul.frias\\PycharmProjects\\SeleniumProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1751938081493, "stop": 1751938081504}], "start": 1751938051190, "stop": 1751938081504}